{{- include "ffc-helm-library.container-secret" (list . "ffc-lnr-map-web.container-secret") -}}
{{- define "ffc-lnr-map-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUser }}
{{- end -}}
